name: CMake MSVC

on: push

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3
      - name: fetch yasm
        run: python -c "from urllib.request import urlretrieve; urlretrieve('http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe', 'yasm.exe')"
      - name: add yasm to path
        run: echo "%GITHUB_WORKSPACE%" >> %GITHUB_PATH%
      - name: CMake
        run: cd ports\cmake && cmake -DYASM_ASSEMBLER=%GITHUB_WORKSPACE%\yasm .
      - name: CMake --build
        run: cd ports\cmake && cmake --build .
